server:
    port: 8091

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/esm_stocks_db
        username: root
        password: root
    jpa:
        hibernate: 
            ddl-auto: update