server:
    port: 8090

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
    #   username: root
    #   password: root
      database: esm-company-svc
      auto-index-creation: true
